name: final_alert_guard_admin
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^7.7.0
  intl: ^0.19.0

  dio: ^5.5.0+1
  logger: ^2.3.0

  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3

  flutter_svg: ^2.0.10
  bot_toast: ^4.1.3

  image_picker: ^1.1.1
  cached_network_image: ^3.3.1

  fluttertoast: ^8.2.6

  # Firebase
  flutter_local_notifications: ^17.2.1+2
  firebase_messaging: ^15.0.3
  firebase_storage: ^12.1.1
  firebase_core: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/Poppins-ExtraBold.ttf
          weight: 800